#!/bin/bash

VPN_NAME="eesyvpn"

# Certification Authority
CAHOME=/etc/eesyvpn/$VPN_NAME
CRT_DIR=$CAHOME/certs
CRT_REVOKED_DIR=$CRT_DIR/revoked
KEY_DIR=$CAHOME/private
KEY_REVOKED_DIR=$KEY_DIR/revoked
CSR_DIR=$CAHOME/csr
CSR_REVOKED_DIR=$CSR_DIR/revoked
PEM_DIR=$CAHOME/pem
PEM_REVOKED_DIR=$PEM_DIR/revoked
CACRT=$CRT_DIR/ca.crt
CAKEY=$KEY_DIR/ca.key
CRL_DIR=$CAHOME/crl
CRLPEM=$CRL_DIR/crl.pem
NEW_CRT_DIR=$CAHOME/misc/ca.db.certs
TA_KEY_DIR=$CAHOME/private
TA_KEY=$TA_KEY_DIR/ta.key
CCD_DIR=$CAHOME/ccd
DH1024=$KEY_DIR/dh1024.pem

# Log configuration
VPN_LOG_DIR="/var/log"
VPN_LOG_NAME="openvpn-$VPN_NAME"
VPN_LOG_FILE="$VPN_LOG_DIR/${VPN_LOG_NAME}.log"
VPN_LOG_STATUS_FILE="$VPN_LOG_DIR/${VPN_LOG_NAME}-status.log"

# OpenSSL
OSSL_CNF_DIR=$CAHOME/openssl
OSSL_CNF=$OSSL_CNF_DIR/openssl.conf
OSSL_INDEX=$OSSL_CNF_DIR/index
OSSL_SERIAL=$OSSL_CNF_DIR/serial

OSSL_VAR_C="FR"
OSSL_VAR_ST="Ile de France"
OSSL_VAR_L="Paris"
OSSL_VAR_O="Easter-eggs"
OSSL_VAR_OU="$OSSL_VAR_O"
OSSL_VAR_EMAIL="postmaster@easter-eggs.com"
OSSL_VAR_CAHOME="$CAHOME"

[ ! -n "$OSSL_CERT_TYPE" ] && OSSL_CERT_TYPE="client, email"

OSSL_CERT_SUBJ_FORMAT="/C=$OSSL_VAR_C/ST=$OSSL_VAR_ST/L=$OSSL_VAR_L/O=$OSSL_VAR_O/OU=$OSSL_VAR_OU/CN=%%CN%%/emailAddress=$OSSL_VAR_EMAIL"

# OpenVPN
OVPN_CNF_DIR=$CAHOME/openvpn
OVPN_CNF_CLIENTS_DIR=$OVPN_CNF_DIR/clients
OVPN_CNF_CLIENTS_ZIP_DIR=$OVPN_CNF_CLIENTS_DIR
OVPN_CNF_CLIENTS_TPL=$OVPN_CNF_DIR/client.ovpn.tpl
OVPN_SERVER_CNF=$OVPN_CNF_DIR/openvpn.conf
OVPN_SERVER_LINK=/etc/openvpn/${VPN_NAME}.conf


[ -f /etc/eesyvpn/eesyvpn.conf ] && source /etc/eesyvpn/eesyvpn.conf

function check_ca_structure() {
	# Check structure
	[ ! -d $CAHOME ] && echo "ERROR : Certification Authority directory not found ($CAHOME). Check your configuration" && exit 1
	
	[ ! -f $CACRT ] && echo "ERROR : Certification Authority certificate not found ($CACRT). Check your configuration" && exit 1
	[ ! -f $CAKEY ] && echo "ERROR : Certification Authority key not found ($CAKEY). Check your configuration" && exit 1
	return 0
}

function check_directories() {
	# Create structural directories if not exists
	for dir in $CAHOME $KEY_DIR $KEY_REVOKED_DIR $CRT_DIR $CRT_REVOKED_DIR $CSR_DIR $CSR_REVOKED_DIR $PEM_DIR $PEM_REVOKED_DIR $NEW_CRT_DIR $OVPN_CNF_DIR $OVPN_CNF_CLIENTS_DIR $OVPN_CNF_CLIENTS_ZIP_DIR $OSSL_CNF_DIR $CRL_DIR $TA_KEY_DIR $CCD_DIR
	do
		if [ ! -d $dir ]
		then
			echo -n "  - create $dir : "
			mkdir -p $dir
			chmod 755 $dir
			echo done.
		fi
	done

	# Fix structural directories rights
	chmod 750 $KEY_DIR $CSR_DIR $TA_KEY_DIR $OVPN_CNF_CLIENTS_DIR $PEM_DIR $OSSL_CNF_DIR
	return 0
}

function init_openssl_config() {
	echo -n "INFO : Initialize Certification Authority OpenSSL configuration ($OSSL_CNF) : "
	cp /usr/share/doc/eesyvpn/example/openssl.conf $OSSL_CNF
	sed -i "s/%%C%%/$OSSL_VAR_C/g" $OSSL_CNF
	sed -i "s/%%ST%%/$OSSL_VAR_ST/g" $OSSL_CNF
	sed -i "s/%%L%%/$OSSL_VAR_L/g" $OSSL_CNF
	sed -i "s/%%O%%/$OSSL_VAR_O/g" $OSSL_CNF
	sed -i "s/%%OU%%/$OSSL_VAR_OU/g" $OSSL_CNF
	sed -i "s/%%EMAIL%%/$OSSL_VAR_EMAIL/g" $OSSL_CNF
	sed -i "s@%%CAHOME%%@$OSSL_VAR_CAHOME@g" $OSSL_CNF
	echo done.
	return 0
}

function check_openssl() {
	# OpenSSL
	[ ! -f $OSSL_CNF ] && init_openssl_config
	[ ! -f $OSSL_INDEX ] && echo "INFO : Initialize OpenSSL index file" && touch "$OSSL_INDEX"
	[ ! -f $OSSL_SERIAL ] && echo "INFO : Initialize OpenSSL serial file" && echo -n 01 > $OSSL_SERIAL
	[ ! -f $DH1024 ] && echo "INFO : Generate OpenSSL dh1024.pem file" && openssl dhparam -out $DH1024 1024
	return 0
}

function check_openvpn() {
	# OpenVPN
	[ ! -d $OVPN_CNF_DIR ] && echo "INFO : Create OpenVPN configuration directory" && mkdir $OVPN_CNF_DIR
	[ ! -f $OVPN_CNF_CLIENTS_TPL ] && echo "ERROR : OpenVPN configuration template file nod found ($OVPN_CNF_CLIENTS_TPL). Check your configuration" && exit 1
	return 0
}

function to_humain_date() {
	echo $1|sed 's/\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)Z/20\1\/\2\/\3 \4:\5:\6/'
}

# Parameters
action=$1
name=$2

function usage() {
        echo "Usage: $0 {create|recreate|view|renew|revoke|sign|update-crl|makeconf|makezipconf} {CERTIFICATE_NAME}"
	echo
	echo "To initialize your CA, run $0 initialize [your.server.fqdn]"
}

if [ ! -n "$action" ]
then
	usage
	exit 0
fi

if [ ! -n "$name" -a "$action" != "update-crl" -a "$action" != "list" ]
then
	echo CERTIFICATE_NAME not defined
	usage
        exit 0
fi

[ "$action" != "initialize" ] && check_openssl && check_directories && check_openvpn

# Main
case $action in
	create)
		if [ -f $CRT_DIR/$name.crt  -o -f $KEY_DIR/$name.key -o -f $PEM_DIR/$name.pem ]
		then
			echo "Name $name already used"
			exit 1
		fi

		echo "Generate key file : "
		openssl genrsa -out $KEY_DIR/$name.key 2048
		echo done.
		echo

		echo "Fix key file access right : "
		chmod 0600 $KEY_DIR/$name.key
		echo done.
		echo

		$0 makecert "$name" "$3"

		if [ "$3" != '--without-config' -a "$4" != '--without-config' -a "$3" != '--server' ]
		then
			$0 makeconf $name
			$0 makezipconf $name
		fi
	;;
	makecert)
		if [ ! -f $KEY_DIR/$name.key ]
		then
			echo "Key file of $name not found"
			exit 1
		fi

		echo -n "Generate csr file : "
		SUBJ=$( echo "$OSSL_CERT_SUBJ_FORMAT"|sed "s/%%CN%%/$name/g" )
		openssl req -new -key $KEY_DIR/$name.key -out $CSR_DIR/$name.csr -config $OSSL_CNF -subj "$SUBJ"
		echo done.
		echo
		
		$0 sign $name "$3"

		if [ ! -f "$CRT_DIR/$name.crt" ]
		then
			echo "ERROR : Certificate file not found ($CRT_DIR/$name.crt)."
			exit 1
		fi

		echo -n "Generate pem file : "
		cat $KEY_DIR/$name.key >  $PEM_DIR/$name.pem
		cat $CRT_DIR/$name.crt >> $PEM_DIR/$name.pem
		echo done.
	;;
	recreate)
		if [ ! -f $CRT_DIR/$name.crt ]
		then
			echo "This name $name not currently exist"
			exit 1
		fi
		$0 revoke $name
		$0 create $name "$3"
	;;
	renew)
		if [ ! -f $CRT_DIR/$name.crt ]
		then
			echo "This name $name not currently exist"
			exit 1
		fi
		$0 revoke $name --preserve-key
		$0 makecert $name "$3"

		$0 makeconf $name
		$0 makezipconf $name
	;;
	sign)
		if [ ! -f $CSR_DIR/$name.csr ]
		then
			echo "CSR not found: $CSR_DIR/$name.csr"
			exit 1
		fi
		if [ "$3" == "--server" ]
		then
			EXT="-extensions server"
		else
			EXT=""
		fi
		openssl ca -config $OSSL_CNF -batch $EXT -out $CRT_DIR/$name.crt -infiles $CSR_DIR/$name.csr
		echo
		echo "CA verifying : "
		openssl verify -CAfile $CACRT $CRT_DIR/$name.crt
		echo
	;;
	revoke)
		if [ ! -f $CRT_DIR/$name.crt ]
		then
			echo "CRT not found: $CRT_DIR/$name.crt"
			exit 1
		fi
		echo "Revoke CRT : "
		openssl ca -config $OSSL_CNF -revoke $CRT_DIR/$name.crt
		echo done.
		echo
		echo -n "Move old certificate in revoked directory : "
		mv -f $CRT_DIR/$name.crt $CRT_REVOKED_DIR/
		mv -f $PEM_DIR/$name.pem $PEM_REVOKED_DIR/
		mv -f $CSR_DIR/$name.csr $CSR_REVOKED_DIR/
		[ "$3" != "--preserve-key" ] && mv -f $KEY_DIR/$name.key $KEY_REVOKED_DIR/
		echo done.

		$0 update-crl
	;;
	update-crl)
		echo "Update CRL ($CRLPEM) : "
		openssl ca -gencrl -config $OSSL_CNF -crldays 31 -out $CRLPEM
		echo done.
	;;
	makeconf)
		ovpn=$OVPN_CNF_CLIENTS_DIR/${name}.ovpn
		echo "Make OpenVPN client config file :"
		echo "  $ovpn"
		cat $OVPN_CNF_CLIENTS_TPL|unix2dos|sed "s/%%CN%%/${name}/g" > $ovpn

		if [ $( grep -c '%%CERT%%' $ovpn ) -gt 0 ]
		then
			perl -pi -e "s(%%CERT%%)($( cat $CRT_DIR/${name}.crt ))" $ovpn
		fi

		if [ $( grep -c '%%KEY%%' $ovpn ) -gt 0 ]
		then
			perl -pi -e "s(%%KEY%%)($( cat $KEY_DIR/${name}.key ))" $ovpn
		fi

		if [ $( grep -c '%%CACRT%%' $ovpn ) -gt 0 ]
		then
			perl -pi -e "s(%%CACRT%%)($( cat $CACRT ))" $ovpn
		fi

		if [ $( grep -c '%%TA_KEY%%' $ovpn ) -gt 0 ]
		then
			perl -pi -e "s(%%TA_KEY%%)($( cat $TA_KEY ))" $ovpn
		fi
		echo done.
	;;
	makezipconf)
		ADD_IN_ZIP="$OVPN_CLIENT_INSTALLER"
		ovpn=$OVPN_CNF_CLIENTS_DIR/$name.ovpn
		[ ! -f $ovpn ] && $0 makeconf $name
		if [ $( grep -c "cert ${name}.crt" $ovpn ) -gt 0 ]
		then
			ADD_IN_ZIP="$ADD_IN_ZIP $CRT_DIR/${name}.crt"
		fi

		if [ $( grep -c "key ${name}.key" $ovpn ) -gt 0 ]
		then
			ADD_IN_ZIP="$ADD_IN_ZIP $KEY_DIR/${name}.key"
		fi

		if [ $( grep -c "ca $( basename $CACRT )" $ovpn ) -gt 0 ]
		then
			ADD_IN_ZIP="$ADD_IN_ZIP $CACRT"
		fi

		if [ -f $TA_KEY -a $( grep -c "tls-auth $( basename $TA_KEY )" $ovpn ) -gt 0 ]
		then
			ADD_IN_ZIP="$ADD_IN_ZIP $TA_KEY"
		fi

		if [ -n "$ADD_IN_ZIP" ]
		then
			zip=$OVPN_CNF_CLIENTS_ZIP_DIR/${name}.zip
			echo "Make OpenVPN client zip config file : $zip"
			[ -f $zip ] && echo  -n "Remove old OpenVPN client config zip file : " && rm -f $zip && echo done. || echo error.
			zip -r $zip -j $ADD_IN_ZIP $ovpn
			echo done.
		else
			echo "No additional file detected. Don't generate zip file, just use OpenVPN client config file : $ovpn"
		fi
	;;
	initialize)
		echo "Initialize CA with servername $name :"

		if [ -e "$CAHOME" -o -e "$CAKEY" -o -e "$CACRT" ]
		then
			echo "ERROR : Installation already initialized."
			echo
			echo "  If you want to reset your installation, please remove manually"
			echo "  configuration directory :"
			echo "    $CAHOME"
			exit 1
		fi

		echo "Build Easy RSA temporary directory : "
		EASYRSA_DIR=$( mktemp -d -u )
		make-cadir $EASYRSA_DIR
		[ ! -d "$EASYRSA_DIR" -o ! -e "$EASYRSA_DIR/build-ca" ] && echo "ERROR : problem occured creating Easy RSA directory." && exit 1
		echo done.

		EESYVPN_KEY_DIR=$KEY_DIR
		cd "$EASYRSA_DIR"

		echo "Initialize SSL variables :"

		source ./vars
		export KEY_COUNTRY="$OSSL_VAR_C"
		export KEY_PROVINCE="$OSSL_VAR_ST"
		export KEY_CITY="$OSSL_VAR_L"
		export KEY_ORG="$OSSL_VAR_O"
		export KEY_EMAIL="$OSSL_VAR_EMAIL"
		#export KEY_CN="$name"
		export KEY_NAME="$name"
		export KEY_OU="$OSSL_VAR_OU"

		./build-ca

		KEY_DIR=$EESYVPN_KEY_DIR
		echo "Structural directories of CA : "
		check_directories
		echo done.
		
		echo "Copy generated files in CA directory :"
		echo -n "  - Key ($CAKEY) : "
		mv keys/ca.key $CAKEY
		echo done.

		echo -n "  - Certificate ($CACRT) : "
		mv keys/ca.crt $CACRT
		echo done.

		echo "Clean Easy RSA temporary directory :"
		rm -fr "$EASYRSA_DIR"
		echo done.

		if [ ! -f "$OVPN_CNF_CLIENTS_TPL" ]
		then
			echo -n "Create client template configuration : "
			cp /usr/share/doc/eesyvpn/example/client.ovpn.tpl $OVPN_CNF_CLIENTS_TPL
			sed -i "s/%%HOSTNAME%%/$name/g" $OVPN_CNF_CLIENTS_TPL
			echo done.
		fi

		$0 update-crl

		echo "Clean previous generated TA key and build an new one : "
		[ -f $TA_KEY ] && rm -f $TA_KEY
		openvpn --genkey --secret $TA_KEY
		echo done

		echo -n "Create VPN server key and certificate :"
		$0 create "$name" --server --without-config
		echo done.
		SRVKEY=$KEY_DIR/${name}.key
		SRVCRT=$CRT_DIR/${name}.crt

		echo "Fixed configuration files access rights :"
		echo -n "  - Key files : "
		chmod 0600 $CAKEY $TA_KEY $SRVKEY 
		echo done.

		echo -n "  - Certificates files : "
		chmod 0644 $CACRT $SRVCRT
		echo done.

		if [ ! -f "$OVPN_SERVER_CNF" ]
		then
			echo -n "Create server configuration : "
			cp /usr/share/doc/eesyvpn/example/openvpn.conf $OVPN_SERVER_CNF
			sed -i "s|%%HOSTNAME%%|$name|g" $OVPN_SERVER_CNF
			sed -i "s|%%VPN_NAME%%|$VPN_NAME|g" $OVPN_SERVER_CNF
			sed -i "s|%%SRVKEY%%|$SRVKEY|g" $OVPN_SERVER_CNF
			sed -i "s|%%SRVCRT%%|$SRVCRT|g" $OVPN_SERVER_CNF
			sed -i "s|%%CACRT%%|$CACRT|g" $OVPN_SERVER_CNF
			sed -i "s|%%DH1024%%|$DH1024|g" $OVPN_SERVER_CNF
			sed -i "s|%%TA_KEY%%|$TA_KEY|g" $OVPN_SERVER_CNF
			sed -i "s|%%CRLPEM%%|$CRLPEM|g" $OVPN_SERVER_CNF
			sed -i "s|%%CCD_DIR%%|$CCD_DIR|g" $OVPN_SERVER_CNF
			sed -i "s|%%VPN_LOG_FILE%%|$VPN_LOG_FILE|g" $OVPN_SERVER_CNF
			sed -i "s|%%VPN_LOG_STATUS_FILE%%|$VPN_LOG_STATUS_FILE|g" $OVPN_SERVER_CNF
			ln -s $OVPN_SERVER_CNF $OVPN_SERVER_LINK
			echo done.

			/etc/init.d/openvpn start $( basename $OVPN_SERVER_CNF|sed 's/\.conf$//' )
		fi
	;;
	list)
		if [ "$2" == "--csv" ]
		then
			CSV=1
		else
			CSV=0
			echo "ID | State | Type   | Expiration date     | Revocation date     | Name"
			echo "---+-------+--------+---------------------+---------------------+------------------------------"
		fi
		IFS="
"
		for line in $( cat $OSSL_INDEX )
		do
			state=$( echo "$line"| cut -f1 )
			expdate=$( echo "$line"|cut -f2 )
			expdate=$( to_humain_date $expdate )
			revdate=$( echo "$line"|cut -f3 )
			revdate=$( to_humain_date $revdate )
			id=$( echo "$line"|cut -f4 )
			fields=$( echo "$line"|cut -f6 )
			cn=$( echo "$fields"|sed 's/^.*CN=\([^\/]*\).*$/\1/' )
			if [ $( openssl x509 -noout -text -in "$NEW_CRT_DIR/$id.pem"|grep -c "SSL Server" ) -eq 1 ]
			then
				typ="server"
			else
				typ="client"
			fi

			if [ $CSV -eq 1 ]
			then
				echo "'$id';'$cn';'$state';'$typ';'$expdate';'$revdate'"
				continue
			fi
			if [ "$revdate" == "" ]
			then
				revdate="                   "
			fi
			echo "$id | $state     | $typ | $expdate | $revdate | $cn"
		done
	;;
	view)
		if [ -f "$CRT_DIR/$name.crt" ]
		then
			crt="$CRT_DIR/$name.crt"
		elif [ -f "$NEW_CRT_DIR/$name.pem" ]
		then
			crt="$NEW_CRT_DIR/$name.pem"
		else
			echo "Invalid name"
			exit 1
		fi
		openssl x509 -noout -text -in "$crt"
	;;
	namebyid)
		if [ -f "$NEW_CRT_DIR/$name.pem" ]
		then
			openssl x509 -noout -text -in "$NEW_CRT_DIR/$name.pem"|grep Subject:|sed 's/^.*CN=\([^ ,]*\).*$/\1/'
		else
			echo "Invalid ID"
			exit 1
		fi
	;;
        *)
		echo "Invalid Action"
                usage
                exit 0
        ;;
esac

exit 0
